version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "any-framework-nginx"
    ports:
      - 6543:80
    depends_on:
      - web
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  mysql:
    image: mysql:8.0.25
    container_name: "any-framework-mysql"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: any-framework
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"

  web:
    build: ./docker/php
    container_name: "any-framework-php"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html/
